services:
  albyhub:
    container_name: albyhub
    image: ghcr.io/getalby/hub:${VERSION}
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ${HOST_ALBY_HUB_DATA_DIR}:/data
    network_mode: "host"
    environment:
      WORK_DIR: /data
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
